services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - main
    restart: unless-stopped
