services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - main_data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_SECURE=false
    env_file:
      - ./.env
    depends_on:
      - minio
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - streamlit_data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=http://main:8000
    depends_on:
      - main
    restart: unless-stopped

      # MinIO service for object storage
  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z.fips
    ports:
      - 3005:9001  # Console port
      - 9000:9000  # API port
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data  # Persistent storage for MinIO

volumes:
  main_data:
  streamlit_data:
  minio_data:
